 DATE	1901	1	31                                    
 DATE	1901	3	2                                     
 DATE	1901	4	1                                     
 OPEN 'Producer2'                                  
 OPEN 'Injector2'                                  
 HEATR   *CON 0                                    
 UHTR    *CON 0                                    
 DATE	1901	5	1                                     
 DATE	1901	5	31                                    
 DATE	1901	6	30                                    
 DATE	1901	7	30                                    
 DATE	1901	8	29                                    
 DATE	1901	9	28                                    
 DATE	1901	10	28                                   
 DATE	1901	11	27                                   
 DATE	1901	12	27                                   
 DATE	1902	1	26                                    
 DATE	1902	2	25                                    
 DATE	1902	3	27                                    
 DATE	1902	4	26                                    
 DATE	1902	5	26                                    
 DATE	1902	6	25                                    
 STOP
